server:
  port: 8081
#Redis cache 过期时间设置
redis:
  cache:
    expiration: 3600


spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: zeal
    password: zeal3230

# datasoure默认使用HikariCP连接池
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/zealsay?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    password: zeal
    username: zeal
    hikari:
      driver-class-name:  com.mysql.jdbc.Driver
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等


qiniu:
  accessKey: hM2cBDEM0FTYzpXbigRW90kV12NhhzhFM3jCzurJ
  secretKey: ENC(HM/K0KmtFoZSBhGDEA0Ez71ePTncZlQ954DfLNMZuOftKZq+2WR+dCXH9QEsf768q9wwd92RXLE=)
  bucket: pigcloud
  qiniuHost: http://p0hpm86wj.bkt.clouddn.com/

logging:
  config: classpath:logback.xml

